set_property SRC_FILE_INFO {cfile:D:/C/fac3/sem1/ssc/PROIECT_SSC/PROIECT_SSC.srcs/constrs_1/new/constrain.xdc rfile:../../../PROIECT_SSC.srcs/constrs_1/new/constrain.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports clk]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15 [get_ports rst]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K18 [get_ports {start_conv[0]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports finish_op]
