# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/C/fac3/sem1/ssc/PROIECT_SSC/PROIECT_SSC.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_1_3/design_1_axi_bram_ctrl_1_3.xci
# IP: The module: 'design_1_axi_bram_ctrl_1_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/C/fac3/sem1/ssc/PROIECT_SSC/PROIECT_SSC.gen/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_1_3/design_1_axi_bram_ctrl_1_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_bram_ctrl_1_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/C/fac3/sem1/ssc/PROIECT_SSC/PROIECT_SSC.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_1_3/design_1_axi_bram_ctrl_1_3.xci
# IP: The module: 'design_1_axi_bram_ctrl_1_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/C/fac3/sem1/ssc/PROIECT_SSC/PROIECT_SSC.gen/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_1_3/design_1_axi_bram_ctrl_1_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_bram_ctrl_1_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
